; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File
;
; Documentación: https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

lib_deps =
    bblanchon/ArduinoJson@^7.4.3
    esphome/ESPAsyncWebServer-esphome@^3.4.0

monitor_speed   = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DLED_BUILTIN=2

; FIX: cambio de SPIFFS a LittleFS (SPIFFS deprecado en Arduino Core 3.x)
board_build.filesystem    = littlefs
board_build.partitions    = default.csv

; Ajuste de partición del sistema de archivos
; Estos valores equivalen a los anteriores de SPIFFS pero para LittleFS
board_build.littlefs_start  = 0x291000
board_build.littlefs_size   = 1441792
